### PR TITLE
Add support for Eigen 3.4.0

### LINKED ISSUE #139: Eigen::NumTraits does not define infinity() or quiet_NaN()
Trying to build this simple (and contrived) test program with latest CppAD and Eigen 3.4.0 (e.g. as packaged in Fedora 36) fails (it worked in Fedora 35, which ships Eigen 3.3.9):

```
#include <Eigen/Eigenvalues>
#include <Eigen/Core>
#include <cppad/cppad.hpp>
#include <cppad/example/cppad_eigen.hpp>

typedef CppAD::AD<double> ADFloat;
typedef Eigen::Matrix<ADFloat, Eigen::Dynamic, Eigen::Dynamic> ADMatrix;
typedef Eigen::SelfAdjointEigenSolver<ADMatrix::PlainObject> EigenSolver;

int main() {
  ADMatrix x(3, 3);
  EigenSolver solver;
  solver.compute(x);
  return 0;
}
```

Compilation fails with

```
/usr/include/eigen3/Eigen/src/Core/MathFunctionsImpl.h:84:43: error: ‘infinity’ is not a member of ‘Eigen::NumTraits<CppAD::A
D<double> >’
   84 |     return NumTraits<RealScalar>::infinity();
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/include/eigen3/Eigen/src/Core/MathFunctionsImpl.h:86:44: error: ‘quiet_NaN’ is not a member of ‘Eigen::NumTraits<CppAD::
AD<double> >’
   86 |     return NumTraits<RealScalar>::quiet_NaN();
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

This appears to be because
 1. Eigen now tries to use `NumTraits<RealScalar>::infinity()` and `NumTraits<RealScalar>::quiet_NaN()` in the `positive_real_hypot()` function in `Eigen/src/Core/MathFunctionsImpl.h` as of commit [bde674164](https://gitlab.com/libeigen/eigen/-/commit/bde6741641b7c677d901cd48db844fcea1fd32fe).
 2. CppAD's implementation of `Eigen::NumTraits` in `cppad/example/cppad_eigen.hpp` does not define `infinity()` or `quiet_NaN()`.

### PR DESCRIPTION
**Pull request by benmwebb**
We provide a specialization of Eigen::NumTraits
for CppAD::AD classes. However, in Eigen 3.4.0
as a result of commit
https://gitlab.com/libeigen/eigen/-/commit/bde674164
Eigen (in Core/MathFunctionsImpl.h) now tries to use
NumTraits<RealScalar>::infinity() and
NumTraits<RealScalar>::quiet_NaN(), which our
specialization does not provide. Add these two methods,
and also allow Eigen to call std::isinf() and
std::isnan() on AD classes. Closes #139.

### CODE REVIEW

**Comment by bradbell** [comment]
This looks great. Thanks.
I have created a local branch corresponding to the pull request and have fixed some documentation problems.
The documentation is current in omhelp, but I plan to automatically convert it to sphinx to make it easier for others to use.
I have a convertor, but it needs more work and I am currently working on other things.

One thing  I have avoided adding template specializations for AD types in the std namespace. See
    https://en.cppreference.com/w/cpp/language/extending_std
where the following text appears:

Specializations of [std::numeric_limits](https://en.cppreference.com/w/cpp/types/numeric_limits) must define all members declared static const (until C++11)static constexpr (since C++11) in the primary template, in such a way thatey are usable as [integral constant expressions](https://en.cppreference.com/w/cpp/language/constant_expression).

I do not think that AD types correspond to integral constant expressions, but perhaps they do ?

I think it will work to have the definition of isinf and isnan in the CppAD namespace ?

**Comment by benmwebb** [comment]
I don't think it would work to put the `isinf` and `isnan` overloads in the CppAD namespace, since they are called by Eigen deep inside its `Core/MathFunctions.h` in the `Eigen::internal` namespace:

```
template<typename T>
EIGEN_DEVICE_FUNC
typename internal::enable_if<(!internal::is_integral<T>::value)&&(!NumTraits<T>::IsComplex),bool>::type
isinf_impl(const T& x)
{
  #if defined(EIGEN_GPU_COMPILE_PHASE)
    return (::isinf)(x);
  #elif EIGEN_USE_STD_FPCLASSIFY
    using std::isinf;
    return isinf EIGEN_NOT_A_MACRO (x);
  #else
    return x>NumTraits<T>::highest() || x<NumTraits<T>::lowest();
  #endif
}
```

(the `EIGEN_USE_STD_FPCLASSIFY` case is the one that's called, in my testing)

Eigen isn't going to look in the CppAD namespace to find `isinf`, surely. It might work though if we define `isinf` in the `Eigen::internal` namespace, if that seems cleaner to you?

**Comment by bradbell** [comment]
I see the problem, Eigen is using ``::isinf`` or ``std::isinf`` instead of just ``isinf``, so it is requiring a change to to standard namespace. I will change pull_140 to specialize in the standard namespace as you suggested.

**Comment by bradbell** [comment]
@benmwebb I have changed cppad_eigen.hpp back to the way you had it. Please test the branch
https://github.com/coin-or/CppAD/tree/pull_140

and see if it works for you. If so, I will merge it into the master.

**Comment by bradbell** [comment]
I have not heard back on your testing and I have a bug fix to merge into the master, so I first merged this pull request using the pull_140 branch.

**Comment by benmwebb** [comment]
> I see the problem, Eigen is using ::isinf or std::isinf instead of just isinf, so it is requiring a change to to standard namespace

Right, I wasn't super happy poking around in `std` either but could find no other solution. This is also what the libMesh folks did to make Eigen 3.4 work with their dual number class: libMesh/MetaPhysicL#21

> Please test the branch https://github.com/coin-or/CppAD/tree/pull_140

@bradbell I just tested master and... it *nearly* works, in that my simple test case passes now but unfortunately not the full code that originally failed. Looks like Eigen *also* tries to call `std::isfinite` on AD classes. But that's an easy fix; I'll add a second PR for it.
