### ISSUE TITLE
clang-7 debugging error

### ISSUE THREAD

**Issue by han-so1omon** [coin-or/CppAD#31]
When compiling a program that includes CppAD with clang-7, the following error is thrown:
```
cppad/utility/check_simple_vector.hpp:134:10: error: no member named 'value' in 'CppAD::ok_if_S_same_as_T<double, float>'
```

The line in question is as shown below (`const Scalar& x` is input to the function in question):
```
typedef typename Vector::value_type value_type;

struct ok_if_S_same_as_T<Scalar, value_type x_copy;

x_copy.value = x;
```

The structure in question is defined as below:
```
template <class S, class T> struct ok_if_S_same_as_t { };

template <class T> struct ok_if_S_same_as_T<T,T> {T value;};
```

The member value is referenced again on line 159 of the same file, and again an error is thrown during compilation with clang-7. I guess this has something to do with how the templated struct members are defined in the class after compilation. In this case, the member `T value` is not defined in the struct that is instantiated (or it seems not to be just by looking at the struct definition).

**Comment by bradbell** [comment]
Thanks for the bug report. It would help if you created an example. 

Perhaps you could
    cp bug/template.sh bug/check_simple_vector.sh
and then edit check_simple_vector.sh so that it demonstrates the bug
and I would then be able to reproduce the problem by executing
    bug/check_simple_vector.sh

Perhaps check_simple_vector.sh would be very short and you could just past it into the comment window for this bug.

**Comment by bradbell** [comment]
I added an example test clang compliation of checking simple vectors:
https://github.com/coin-or/CppAD/blob/master/bug/clang_simple.sh

It works fine with clang version 6.0.0 (tags/RELEASE_600/final)
Please try running 
bug/clang_simple.sh
to see if it fails with clang 7

**Comment by han-so1omon** [comment]
I'm going to try to debug this problem today and tomorrow. My suspicion is that the error is somehow expected behavior but with a strange error message. The stack trace seems related to this call, which does some type casting:
```
    CppAD::vector<CppAD::AD<double>> outputVar(n);
    outputVar = tiny_dnn::convertToAdVec<CppAD::AD<double>>(v->at(i).out);

    CppAD::Independent(outputVar);
   
    CppAD::vector<CppAD::AD<double>> objectiveVar(m);
    objectiveVar[0] = tiny_dnn::convertToAdVec<CppAD::AD<double>>(objective(outputVar,
        v->at(i).advantageValues, v->at(i).in,
        v->at(i).value, v->at(i).valueTarget, policy));
    
    CppAD::ADFun<double> surrogateVars(outputVar,objectiveVar); 

    v->at(i).objectiveValue = (double)objectiveVar[0];

    tiny_dnn::vec_t x(n);
    x = v->at(i).out;
    v->at(i).gradientValues = surrogateVars.Jacobian(x);
```

tiny_dnn::vec_t is: `typedef std::vector<float_t, aligned_allocator<float_t, 64>> vec_t;`

**Comment by bradbell** [comment]
I have fixed the conversion warnings, in the Cppad source, generated by clang 6.0; see 08-13 on
https://coin-or.github.io/CppAD/doc/whats_new_18.htm#08-13

There are still warnings on some of the supporting software, like Ipopt and Adolc
(perhaps CppAD should treat these packages like eigen; i.e., give up on them fixing their warnings
and treat the corresponding include directories like system directories).

You can use clang to build the CppAD tests, that do not use adolc or ipopt, using:
bin/run_cmake.sh --no_adolc  --no_ipopt --clang
cd build
make check

You can build and run one test using
bin/test_one.sh dir/file.cpp
where dir/file.cpp is the path the individual test.

**Comment by bradbell** [comment]
Is this still a problem for you ? If not, would you please close this issue.

**Comment by bradbell** [comment]
@han-so1omon I am closing this bug. If it is still a problem for you, please re-open it.
